### ISSUE TITLE
Unable to import package

### ISSUE THREAD

**Issue by monicau** [UMNLibraries/primo-explore-hathitrust-availability#14]
Hello, I'm having trouble getting this package to run properly in my local dev environment. 

I've tried two approaches:

1) I added this to `custom.module.js`
```
import 'primo-explore-hathitrust-availability';

var app = angular.module('viewCustom', ['angularLoad', 'hathiTrustAvailability']);

app.component('prmSearchResultAvailabilityLineAfter', {
    template: '<hathi-trust-availability ignore-copyright="true"></hathi-trust-availability>'
  });
```
and ran my local development with `gulp run --view <my_view_name> --ve`. I get this error in the browser console:
```
Uncaught ReferenceError: require is not defined
```
2) I also tried editing `custom.js` directly and passed the `--browserify` flag for the run command.
```
import 'primo-explore-hathitrust-availability';

var app = angular.module('viewCustom', ['angularLoad', 'hathiTrustAvailability']);

app.component('prmSearchResultAvailabilityLineAfter', {
  template: '<hathi-trust-availability ignore-copyright="true"></hathi-trust-availability>'
});
```
`gulp run --browserify --view <my_view_name> --ve` 

I get this error in the console: 
```
Uncaught SyntaxError: Cannot use import statement outside a module
```

Am I doing something incorrectly? 

Thank you!

**Comment by gpeterso** [comment]
Hi @monicau, 

Regarding the first approach that you tried, does it work it you completely remove this line?
`import 'primo-explore-hathitrust-availability';` 

The Primo Dev Environment's default (non-Browserify) build process concatenates all JS files (as described [here](https://github.com/UMNLibraries/primo-explore-hathitrust-availability/issues/11#issuecomment-658937787)), so it shouldn't be necessary to explicitly `import`/`require` modules unless you're using the `--browserify` build option. 

For the sake of completeness, I'll also note that if you *do* want to use the `--browserify` build option, you'll need to create a `main.js` file that explicitly imports modules as needed.

**Comment by monicau** [comment]
Hi @gpeterso 

Thank you for your help! The import errors are gone now.

I have another Primo addon, BrowZine, that's using the same directive "prmSearchResultAvailabilityLineAfter". I'm getting an error:
```
Multiple directives [prmSearchResultAvailabilityLineAfter, prmSearchResultAvailabilityLineAfter] asking for new/isolated scope on: <prm-search-result-availability-line-after parent-ctrl="$ctrl">
```
Would it still work if we combine the component calls of BrowZine and HathiTrust together like this:
```
app.component('prmSearchResultAvailabilityLineAfter', {
  bindings: { parentCtrl: '<' },
  controller: 'prmSearchResultAvailabilityLineAfterController',
  template: '<hathi-trust-availability ignore-copyright="true"></hathi-trust-availability>'
});
```
There are no errors and I'm waiting for my librarian colleagues to test it out.. but I'd like to confirm with you to be sure.  Apologies if this is more of an Angular question and not one specific to your addon. I'm still very new to this framework.


Thanks again!

**Comment by gpeterso** [comment]
Glad to hear it's working @monicau! 

Ah, yeah... [Third Iron's instructions](https://thirdiron.atlassian.net/wiki/spaces/BrowZineAPIDocs/pages/79200260/Ex+Libris+Primo+Integration) for the BrowZine plugin seem to assume that you don't need more than one `prmSearchResultAvailabilityLineAfter` component. There are probably a few ways to get around this. In my case, I wrapped the BrowZine integration into its own component, and then added the component to the `prmSearchResultAvailabilityLineAfter` template like so:

```javascript
app.component('prmSearchResultAvailabilityLineAfter', {
  bindings: { parentCtrl: '<' },
  controller: 'prmSearchResultAvailabilityLineAfterController',
  template: '<browzine></browzine><hathi-trust-availability ignore-copyright="true"></hathi-trust-availability>'
});
```

In case it's helpful, I put an example of a Browzine component implementation in [this gist](https://gist.github.com/gpeterso/0036c64e8ba3b6448fa5b4bb2793cf93).

**Comment by monicau** [comment]
This is very helpful! Thank you for the example and for all of your help @gpeterso!
