### ISSUE TITLE
Displaying on non-owned titles in network zone

### ISSUE THREAD

**Issue by sulfurchesh** [UMNLibraries/primo-explore-hathitrust-availability#9]
First off: Great little tool. Works wonderfully.

We're part of a consortium and have an Institution Zone and Network Zone across a bunch of other institutions.

When we search in the IZ, HT links show as expected.

When we search in the NZ, HT links show on anything they find a match with, whether or not we own it or have access to it.

Is it feasible/possible to hide those (non-)connections?

**Comment by gpeterso** [comment]
Hi @sulfurchesh. We use multiple campuses within a single institution, so pardon my NZ ignorance. Is there something in the PNX record that could be used to distinguish the records that should match HT inventory? 

Here's what I'm thinking. Let's say your institution code is `MY_INST`. If you only wanted to check HT inventory on items held by your institution, you could add a `ng-if` directive to the `hathi-trust-availability` component that looks something like this: 

```html
<hathi-trust-availability ng-if="$parent.$ctrl.result.pnx.delivery.institution.some('MY_INST')" 
></hathi-trust-availability>
```

^ In this case, the component would only check for HT availability if the PNX record contains a `delivery/institution` of "MY_INST". 

Do you think that might work for you?

**Comment by sulfurchesh** [comment]
Geoff: Thanks for the quick feedback. I did some poking in our implementation and found a couple of examples for you to show IZ v NZ.

IZ record (we own, also in HT):
https://ocul-qu.primo.exlibrisgroup.com/permalink/01OCUL_QU/1m1jubc/alma993135583405158

This shows a delivery.bestlocation.organization of 01OCUL_QU

NZ record (we don't own, shows in HT):
https://ocul-qu.primo.exlibrisgroup.com/permalink/01OCUL_QU/1vvea0g/alma991528860305151

This has a null delivery.bestlocation

I tried setting our template to:

    template: '<hathi-trust-availability ng-if="$parent.$ctrl.result.pnx.delivery.bestlocation.organization('01OCUL_QU')" msg="Full Text Available Online at HathiTrust" ignore-copyright="true" entity-id="OurIDP"></hathi-trust-availability>'

And it doesn't show the HT link on either -- I suspect that I've made a stupid error in there somewhere.

**Comment by gpeterso** [comment]
Hey @sulfurchesh. Thanks for the examples. I did not realize the you were using VE. 

I think you're pretty close. If you want to restrict the HT lookup to cases where the `bestlocation` is 01OCLU_QU, then your template would look something like this:

```html
template: '<hathi-trust-availability ng-if="$parent.$ctrl.result.delivery.bestlocation.organization === '01OCUL_QU'" msg="Full Text Available Online at HathiTrust" ignore-copyright="true" entity-id="OurIDP"></hathi-trust-availability>'
```

Alternatively, if you wanted to limit HT lookups to titles that *have at least one copy owned by* 01OCLU_QU, then you might be able to do something like this: 

```html
template: '<hathi-trust-availability ng-if="$parent.$ctrl.result.delivery.holding.some(h => h.organization === '01OCUL_QU')" msg="Full Text Available Online at HathiTrust" ignore-copyright="true" entity-id="OurIDP"></hathi-trust-availability>'
```
